-- MySQL Script generated by MySQL Workbench
-- Thu Oct 31 20:46:34 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`pessoa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pessoa` (
  `idpessoa` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idpessoa`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tarefa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tarefa` (
  `idtarefa` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(45) NOT NULL,
  `datacriacao` DATE NOT NULL,
  `prazo` DATE NOT NULL,
  `prioridade` VARCHAR(45) NOT NULL,
  `pessoa_idpessoa` INT NOT NULL,
  PRIMARY KEY (`idtarefa`, `pessoa_idpessoa`),
  INDEX `fk_tarefa_pessoa_idx` (`pessoa_idpessoa` ASC) VISIBLE,
  CONSTRAINT `fk_tarefa_pessoa`
    FOREIGN KEY (`pessoa_idpessoa`)
    REFERENCES `mydb`.`pessoa` (`idpessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`notificacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`notificacao` (
  `idnotificacao` INT NOT NULL AUTO_INCREMENT,
  `mensagem` VARCHAR(100) NOT NULL,
  `datamensagem` DATE NOT NULL,
  `pessoa_idpessoa` INT NOT NULL,
  `tarefa_idtarefa` INT NOT NULL,
  PRIMARY KEY (`idnotificacao`, `pessoa_idpessoa`, `tarefa_idtarefa`),
  INDEX `fk_notificacao_pessoa1_idx` (`pessoa_idpessoa` ASC) VISIBLE,
  INDEX `fk_notificacao_tarefa1_idx` (`tarefa_idtarefa` ASC) VISIBLE,
  CONSTRAINT `fk_notificacao_pessoa1`
    FOREIGN KEY (`pessoa_idpessoa`)
    REFERENCES `mydb`.`pessoa` (`idpessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_notificacao_tarefa1`
    FOREIGN KEY (`tarefa_idtarefa`)
    REFERENCES `mydb`.`tarefa` (`idtarefa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`historico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`historico` (
  `idhistorico` INT NOT NULL AUTO_INCREMENT,
  `status` VARCHAR(45) NOT NULL,
  `pessoa_idpessoa` INT NOT NULL,
  `tarefa_idtarefa` INT NOT NULL,
  PRIMARY KEY (`idhistorico`, `pessoa_idpessoa`, `tarefa_idtarefa`),
  INDEX `fk_historico_pessoa1_idx` (`pessoa_idpessoa` ASC) VISIBLE,
  INDEX `fk_historico_tarefa1_idx` (`tarefa_idtarefa` ASC) VISIBLE,
  CONSTRAINT `fk_historico_pessoa1`
    FOREIGN KEY (`pessoa_idpessoa`)
    REFERENCES `mydb`.`pessoa` (`idpessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_historico_tarefa1`
    FOREIGN KEY (`tarefa_idtarefa`)
    REFERENCES `mydb`.`tarefa` (`idtarefa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
